### ISSUE TITLE
Add in documentation on the python files

### ISSUE THREAD

**Issue by cjumper919** [cjumper919/text-reporter#2]
Add in documentation on the python files.  Any place that has a '# TODO' marked, or some sort of comment needed for a function please address.

**Comment by abecker919** [comment]
This has been addressed.  License and copyright info is left as TODO, since this is a sandbox project.  Commit that addresses this is posted below:

https://github.com/cjumper919/text-reporter/commit/e0dedfddae1db5f355fec017a0633d8e07b96762
