### ISSUE TITLE
Implement Dockerfile for container setup of app

### ISSUE THREAD

**Issue by cjumper919** [cjumper919/text-reporter#4]
Utililize a Dockerfile for this app to run in the background as a running container.  First thoughts are to use a base alpine linux image, but really just find the easiest, quickest option.

**Comment by abecker919** [comment]
This has been addressed in this code change, referenced below:

https://github.com/cjumper919/text-reporter/tree/396107bebed8dc1350752a93b44b42cf234f01e7
