### ISSUE TITLE
Address http error code handling

### ISSUE THREAD

**Issue by cjumper919** [cjumper919/text-reporter#5]
Address error handling for some basic http request error codes.  Some of these may be 400, 403, 500, etc...

**Comment by abecker919** [comment]
Addressed in commit mentioned below.  I still don't like the way some of these errors are handled, but it will suffice for now.  In the future, I would like to address the HTTP status codes in a better fashion.

https://github.com/cjumper919/text-reporter/commit/a454c2c2902a59e4e9435cddbe2ebcd6e33d19d2
